### PR TITLE
Add logic for resources with Id in a lower level

### PR DESCRIPTION
**Pull request by mitchclarkebase2**

### CODE REVIEW

**Comment by mitchclarkebase2** [comment]
Effectively this is just to prevent the compile from failing on HTTP and NRPE resources which have the Id key in a list called `Hosts`

**Comment by aaronwalker** [comment]
@tarunmenon95 can you please review and test this PR

**Comment by tarunmenon95** [comment]
lgtm

Tested with alarms config with standard resources with `Id` key at top level  and HTTP/NRPE resources with nested `Id` key and compiled as expected.

**Review by tarunmenon95 — APPROVED** [review]
lgtm

Tested with alarms config with standard resources with Id key at top level and HTTP/NRPE resources with nested Id key and compiled as expected.

**Pull request merged**
